stages:

- stage: BuildServices

  pool:
    vmImage: ubuntu-latest
  
    jobs:
    - job: BuildDocker_SalesBookLB
    displayName: Build docker image for SalesBook.LB app
  
    steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          Dockerfile: '**/SalesBook.LB/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest